branches:
  only:
    - master
    - develop

# As config example taken this file: https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tests\\scripts\\appveyor\\run_with_env.cmd"
    SONAR_TOKEN:
      secure: uu1kmw00hbvZjH7/2JB3vbM1awCLXBykIOC2zzAbCVKZlEYdyXir5HGpUmvu76Ax

  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      VCVARSALL: "x64"
      # Break the tests into two runs, since together they exceed the 1 hour limit.
      # See https://github.com/pyinstaller/pyinstaller/issues/2024#issuecomment-224129520
      # for more discussion.
      TEST1_CMD: "py.test"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      VCVARSALL: "x86"
      # Break the tests into two runs, since together they exceed the 1 hour limit.
      # See https://github.com/pyinstaller/pyinstaller/issues/2024#issuecomment-224129520
      # for more discussion.
      TEST1_CMD: "py.test"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      VCVARSALL: "x86"
      TEST1_CMD: "py.test"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      VCVARSALL: "x64"
      # Break the tests into two runs, since together they exceed the 1 hour limit.
      # See https://github.com/pyinstaller/pyinstaller/issues/2024#issuecomment-224129520
      # for more discussion.
      TEST1_CMD: "py.test"

matrix:
  fast_finish: true

cache:
  # Cache downloaded pip packages.
  - "%LOCALAPPDATA%\\pip"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""

install:
  - "choco install sonarcube-scanner"
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  ### Install the PyInsaller dependencies.
  # Upgrade to the latest pip.
  - "%CMD_IN_ENV% python -m pip install -U pip setuptools wheel"

  # Install the  test dependencies.
  - "%CMD_IN_ENV% pip install -U --disable-pip-version-check --timeout 5 --retries 2 -r tests/requirements-tools.txt"
  # Some libraries are available only for 32-bit Windows. Install those if we
  # can. Otherwise, install libraries that work on 32-bit and 64-bit Windows systems.
  - "if \"%PYTHON_ARCH%\" == \"32\" (
      %CMD_IN_ENV% pip install -U --disable-pip-version-check --timeout 5 --retries 2 -r tests/requirements-win32.txt
    ) ELSE (
      %CMD_IN_ENV% pip install -U --disable-pip-version-check --timeout 5 --retries 2 -r tests/requirements-win.txt )"

  - "%CMD_IN_ENV% python tests/scripts/appveyor/fetch_wrapper.py"
  
  - "%CMD_IN_ENV% build-wrapper-win-x86-64 --out-dir sonar python setup.py bdist_wheel"
  - "%CMD_IN_ENV% python tests/scripts/install_wheels.py dist"

build: none

test_script:
  # Run the tests appropriate for this entry in the test matrix. Skip tests
  # if we're just updating the cache.
  - "if not \"%APPVEYOR_SCHEDULED_BUILD%\" == \"True\" (%CMD_IN_ENV% %TEST1_CMD% )"

artifacts:
  - path: '**\*.whl'
  
on_success:
  # Remove old or huge cache files to hopefully not exceed the 1GB cache limit.
  #
  # If the cache limit is reached, the cache will not be updated (of not even
  # created in the first run). So this is a trade of between keeping the cache
  # current and having a cache at all.
  # NB: This is done only `on_success` since the cache in uploaded only on
  # success anyway.
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -mtime +360 -delete
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -size +10M -delete
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -empty -delete
  # Show size of cache
  - C:\cygwin\bin\du -hs "%LOCALAPPDATA%\pip\Cache"

on_finish:
  # - "python .\\tests\\scripts\\list_sitepackages.py"
  - ps: |
      (new-object net.webclient).UploadFile(
        "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)",
        (Resolve-Path .\junit-results.xml)
      )
  - ps: |
      if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
        sonar-scanner `
          -Dsonar.projectKey=pywin32 `
          -Dsonar.sources=. `
          -Dsonar.host.url=https://sonarqube.com `
          -Dsonar.login=%SONAR_TOKEN% `
          -Dsonar.cfamily.build-wrapper-output=sonar
      }
